Update to HTTPClientV2
hmrc/pensions-scheme-frontend pull request #1249
Opened 2024-10-21 14:53 UTC by nonebula

2024-10-22 11:21 UTC, PavelVjalicin requested changes

2024-10-22 11:21 UTC, PavelVjalicin commented on app/handlers/ErrorHandlerWithReturnLinkToManage.scala
> +import scala.concurrent.ExecutionContext.Implicits.global
Introduce (implicit ec: ExecutionContext) as an injectable class inside of class constructor instead.

2024-10-23 13:35 UTC, jamdade-sharad commented on app/handlers/ErrorHandler.scala
> +//  def standardErrorTemplate(pageTitle: String, heading: String, message: String)(implicit request: RequestHeader): Future[Html] = {
remove commented code

2024-10-23 13:36 UTC, nonebula commented on app/handlers/ErrorHandler.scala
> +//  def standardErrorTemplate(pageTitle: String, heading: String, message: String)(implicit request: RequestHeader): Future[Html] = {
Done.

2024-10-23 13:48 UTC, jamdade-sharad approved these changes
approved

2024-10-23 14:21 UTC, merged